CREATE TABLE IF NOT EXISTS N_ONE_ATTRIBUTES
(
	ID        int          not null auto_increment,
	IS_ACTIVE bool         not null DEFAULT TRUE,
	TITLE     varchar(100) not null,
	PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS N_ONE_ITEMS_ATTRIBUTES
(
	ITEM_ID      int not null,
	ATTRIBUTE_ID int not null,
	VALUE        float,
	PRIMARY KEY (ITEM_ID, ATTRIBUTE_ID),
	FOREIGN KEY FK_IA_ITEMS (ITEM_ID)
		REFERENCES N_ONE_ITEMS (ID)
		ON UPDATE RESTRICT
		ON DELETE RESTRICT,
	FOREIGN KEY FK_IA_ATTRIBUTES (ATTRIBUTE_ID)
		REFERENCES N_ONE_ATTRIBUTES (ID)
		ON UPDATE RESTRICT
		ON DELETE RESTRICT,
	INDEX(VALUE)
);
# not null